version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  email:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

#  web:
#    build: .
#    #    volumes:
#    #      - .:/app
#    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#    ports:
#      - 8000:8000
#    environment:
#      - POSTGRES_HOST=db
#    env_file:
#      - .env
#    depends_on:
#      - db

volumes:
  postgres_data:
  redis_data:
