"""create roles table

Revision ID: c150f499eb02
Revises: 51857e69a9c8
Create Date: 2024-08-13 21:16:45.996496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.auth.models import Role

# revision identifiers, used by Alembic.
revision: str = 'c150f499eb02'
down_revision: Union[str, None] = '51857e69a9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(Role.__table__, [
        {'id': 1, 'name': 'admin'},
        {'id': 2,'name': 'user'},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    pass
